- name: openrouter/anthropic/claude-3.7-sonnet
  cache_control: true
  extra_params:
    extra_body:
      provider:
        order: ["Google", "Amazon Bedrock"]
        allow_fallbacks: true
- name: claude-37-default
  use_repo_map: true
  name_override: openrouter/anthropic/claude-3.7-sonnet
  edit_format: diff-fenced
- name: nomap-claude-37
  use_repo_map: false
  name_override: openrouter/anthropic/claude-3.7-sonnet

- name: openrouter/qwen/qwen-2.5-coder-32b-instruct
  extra_params:
    extra_body:
      provider:
        order: ["Lambda", "DeepInfra"]
        allow_fallbacks: true
- name: openrouter/google/gemini-2.5-pro-preview
  overeager: true
  edit_format: diff-fenced
  use_repo_map: false
- name: openrouter/deepseek/deepseek-chat-v3-0324
  use_repo_map: false
  overeager: true
  edit_format: diff
