- name: openrouter/anthropic/claude-3.7-sonnet
  edit_format: diff
  use_repo_map: true
  examples_as_sys_msg: true
  cache_control: true
  editor_edit_format: editor-diff
  extra_params:
    extra_body:
      provider:
        order: ["Google", "Amazon Bedrock"]
        allow_fallbacks: true
- name: openrouter/qwen/qwen-2.5-coder-32b-instruct
  extra_params:
    extra_body:
      provider:
        order: ["Lambda", "DeepInfra"]
        allow_fallbacks: true
