[simples.mise]
cmd = "apt update -y && apt install -y gpg wget curl && install -dm 755 /etc/apt/keyrings && wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null && echo 'deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main' | tee /etc/apt/sources.list.d/mise.list && apt update && apt install -y mise"
sudo = true
check = "which mise"
