[symlinks.waybar]
target = "waybar"
name = "~/.config/waybar/"

[templates.hyprland]
target = "hyprland/hyprland_template.conf"
name = "~/.config/hypr/hyprland.conf"
USER = "dlipin"
SCALING = "2"


[symlinks.hyprland_scripts]
target = "hyprland/scripts"
name = "~/.config/hypr/scripts"


[symlinks.ags]
target = "ags"
name = "~/.config/ags"

[symlinks.zathura]
target = "zathura"
name = "~/.config/zathura"
