theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "battery"
critical = 10


[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%R [%a %m %b]"

