[theme]
name = "slick"

[theme.overrides]
separator = ""

[icons]
name = "awesome6"

[[block]]
block = "custom_dbus"
name = "Pomodoro"
initial_text = "Waiting"

[[block]]
block = "battery"
critical = 10

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%R [%a %d %b]"

