[general]

working_directory = "/home/dima/Projects/rustproglang"
workspace = "2"
layout = """{
    "border": "pixel",
    "current_border_width": 2,
    "floating": "auto_off",
    "geometry": {
       "height": 600,
       "width": 800,
       "x": 0,
       "y": 0
    },
    "marks": [],
    "name": "Alacritty",
    "percent": 1,
    "swallows": [
       {
       // "class": "^Alacritty$",
       // "instance": "^Alacritty$",
       // "machine": "^dev$",
       // "title": "^Alacritty$"
       }
    ],
    "type": "con"
}"""

[[applications]]
command = "zathura /home/dima/Dropbox/Books/programming_rust.pdf"

[[applications]]
command = "alacritty --title nvim"
exec = {commands = ["nvim"]}
