[symlinks.hyprland_scripts]
target = "hyprland/scripts"
name = "~/.config/hypr/scripts"

[templates.hyprland]
target = "hyprland/hyprland_template.conf"
name = "~/.config/hypr/hyprland.conf"
SCALING = "1"
USER = "dima"

[symlinks.kitty]
target = "kitty"
name = "~/.config/kitty"

