[symlinks.hyprland_scripts]
target = "hyprland/scripts"
name = "~/.config/hypr/scripts"

[templates.hyprland]
target = "hyprland/hyprland_template.conf"
name = "~/.config/hypr/hyprland.conf"
SCALING = "1"
USER = "dima"
GTK_THEME = "catppuccin-mocha-mauve-standard+default"

[symlinks.kitty]
target = "kitty"
name = "~/.config/kitty"

[symlinks.ags]
target = "ags"
name = "~/.config/ags"

[symlinks.ags_daemon]
target = "systemd/ags.service"
name = "~/.config/systemd/user/ags.service"

[symlinks.zathura]
target = "zathura"
name = "~/.config/zathura"
