[symlinks.zathura]
target = "zathura/zathurarc"
name = "~/.config/zathura/zathurarc"

[symlinks.hyprland]
target = "hyprland"
name = "~/.config/hypr/"

[symlinks.waybar]
target = "waybar"
name = "~/.config/waybar/"
