[symlinks.zathura]
target = "zathura/zathurarc"
name = "~/.config/zathura/zathurarc"

[symlinks.kitty]
target = "kitty"
name = "~/.config/kitty"

[symlinks.hyprland_scripts]
target = "hyprland/scripts"
name = "~/.config/hypr/scripts"
