[symlinks.hyprland_scripts]
target = "hyprland/scripts"
name = "~/.config/hypr/scripts"

[symlinks.kitty]
target = "kitty"
name = "~/.config/kitty"

# [symlinks.ags]
# target = "ags"
# name = "~/.config/ags"

[symlinks.waybar]
target = "waybar"
name = "~/.config/waybar"

[symlinks.zathura]
target = "zathura"
name = "~/.config/zathura"


[templates.hyprland]
target = "hyprland/hyprland_template.conf"
name = "~/.config/hypr/hyprland.conf"
SCALING = "1"
USER = "dima"
GTK_THEME = "catppuccin-mocha-mauve-standard+default"

[templates.ags_daemon]
target = "systemd/ags_template.service"
name = "~/.config/systemd/user/ags.service"
GTK_THEME = "catppuccin-mocha-mauve-standard+default"
AGS_PATH = "/home/dima/.local/bin"
