[symlinks.nvim]
target = "nvim"
source = "~/.config/nvim"

[symlinks.zsh]
target = "zsh"
source = "~/.config/zsh"

[symlinks.hyprland]
target = "hyprland/hyprland.conf"
source = "~/.config/hypr/hyprland.conf"
