- name: Bootstrap development environment
  hosts: localhost

  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.package:
      name:
        - git
        - tmux
        - baobab
      state: present
