- name: Setup remote pocketbase
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - name: Install needed packages
      become: yes
      ansible.builtin.package:
        name:
          - unzip
          - python3
          - python3-pip
        state: present
    - name: Create a db directory
      file:
        path: "{{ db_dir }}"
        state: directory
    - name: Install github3.py
      pip:
        name: github3.py
        state: present
    - name: Get latest pocketbase release
      community.general.github_release:
        token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') }}"
        user: pocketbase
        repo: pocketbase
        action: latest_release
      register: pocketbase_release
    - name: Unzip pocketbase
      unarchive:
        src: "https://github.com/pocketbase/pocketbase/releases/download/{{ pocketbase_release['tag'] }}/pocketbase_{{ pocketbase_release['tag'] | regex_replace('^v','') }}_linux_amd64.zip"
        dest: "{{ db_dir }}"
        # Uncomment if you don't want to update pocketbase
        creates: "{{ db_dir }}/pocketbase"
        remote_src: yes


